# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Baby Bindery
author: The Design Office
email: john@thedesignoffice.org
description: "Baby Bindery is a web-to-print framework built on Jekyll."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thedesignoffice.github.io/babybindery" # the base hostname & protocol for your site
twitter_username: designofficepvd
github_username: thedesignoffice
instagram_username: designofficepvd
arena_username: john-caserta
vimeo_username: user1072259
medium_username: 
chapters: ["chapter one", demo] # note that if you have a multi-word content type to wrap it in quotes. This is not necessary in your post files, however.
book_width: 8.5in
book_height: 11in
margin: .75in
num_pages: 100
markdown: kramdown
