# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design Studio 2016-18
email: john@thedesignoffice.org
description: > # this means to ignore newlines until "baseurl:"
  RISD GD class
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://risd-gd.github.io/ds16-18" # the base hostname & protocol for your site
twitter_username:
github_username: risd-gd
markdown_ext: "md"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
page_width: "8.5in"
page_height: "11in"
content_types: [conversation, image, text]

# Author details.
john_caserta:
    name: John Caserta
    email: jcaserta@risd.edu
